Drop old graphs_to_h_tigs
It broke with new networkx, and it is not worth fixing since
we no longer use it.

E.g.
```
25-Aug-2018 18:03:02    falcon_unzip/mains/graphs_to_h_tigs.py:648: in find_phased_neighbors
25-Aug-2018 18:03:02        ret_t_node = find_max_phased_in_edge(t_node, s_phase)
25-Aug-2018 18:03:02    falcon_unzip/mains/graphs_to_h_tigs.py:608: in find_max_phased_in_edge
25-Aug-2018 18:03:02        overlap_len = calc_overlap_len(v, w)
25-Aug-2018 18:03:02    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
25-Aug-2018 18:03:02
25-Aug-2018 18:03:02    v = '0010:B', w = '0011:B'
25-Aug-2018 18:03:02
25-Aug-2018 18:03:02        def calc_overlap_len(v, w):
25-Aug-2018 18:03:02    >       if sg.edge[v][w]["src"] == "OP":
25-Aug-2018 18:03:02    E       AttributeError: 'DiGraph' object has no attribute 'edge'
25-Aug-2018 18:03:02
25-Aug-2018 18:03:02    falcon_unzip/mains/graphs_to_h_tigs.py:595: AttributeError
```

Also, we no longer have `find_phased_neighbors()`, so we cannot test it.
So this deletes test/test_graphs_to_h_tigs.py too.